"""notes and repositories

Revision ID: field_notes_0001
Revises:
Create Date: 2026-09-26 17:23:13.782065
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "field_notes_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "field_notes_note",
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("gist", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "field_notes_repository",
        sa.Column("repo", sa.String(), nullable=False),
        sa.Column("gist", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repo"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("field_notes_repository")
    op.drop_table("field_notes_note")
    # ### end Alembic commands ###
